"""Initial migration for sports tables

Revision ID: 205b0d2d3e91
Revises: 
Create Date: 2026-02-14 11:21:00.136285

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '205b0d2d3e91'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('idx_school_emails_processed'), table_name='school_emails')
    op.drop_table('school_emails')
    op.drop_index(op.f('idx_agent_log_agent'), table_name='agent_log')
    op.drop_index(op.f('idx_agent_log_created'), table_name='agent_log')
    op.drop_index(op.f('idx_agent_log_level'), table_name='agent_log')
    op.drop_table('agent_log')
    op.drop_index(op.f('ix_agent_runs_agent_id'), table_name='agent_runs')
    op.drop_index(op.f('ix_agent_runs_created_at'), table_name='agent_runs')
    op.drop_index(op.f('ix_agent_runs_status'), table_name='agent_runs')
    op.drop_table('agent_runs')
    op.drop_table('todoist_tasks')
    op.drop_index(op.f('idx_school_events_child'), table_name='school_events')
    op.drop_index(op.f('idx_school_events_date'), table_name='school_events')
    op.drop_table('school_events')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('school_events',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('email_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('school_id', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('child', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('summary', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('event_date', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('event_end_date', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('event_time', postgresql.TIME(), autoincrement=False, nullable=True),
    sa.Column('event_end_time', postgresql.TIME(), autoincrement=False, nullable=True),
    sa.Column('ics_uid', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('invite_sent_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('gcal_event_id', sa.TEXT(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['email_id'], ['school_emails.id'], name=op.f('school_events_email_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('school_events_pkey')),
    sa.UniqueConstraint('ics_uid', name=op.f('school_events_ics_uid_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('idx_school_events_date'), 'school_events', ['event_date'], unique=False)
    op.create_index(op.f('idx_school_events_child'), 'school_events', ['child'], unique=False)
    op.create_table('todoist_tasks',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('email_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('event_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('todoist_id', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('content', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('due_date', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['email_id'], ['school_emails.id'], name=op.f('todoist_tasks_email_id_fkey')),
    sa.ForeignKeyConstraint(['event_id'], ['school_events.id'], name=op.f('todoist_tasks_event_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('todoist_tasks_pkey'))
    )
    op.create_table('agent_runs',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('agent_id', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('run_type', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('trigger', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('status', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('summary', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('duration_ms', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('tokens_used', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('agent_runs_pkey'))
    )
    op.create_index(op.f('ix_agent_runs_status'), 'agent_runs', ['status'], unique=False)
    op.create_index(op.f('ix_agent_runs_created_at'), 'agent_runs', ['created_at'], unique=False)
    op.create_index(op.f('ix_agent_runs_agent_id'), 'agent_runs', ['agent_id'], unique=False)
    op.create_table('agent_log',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('agent', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('level', sa.TEXT(), server_default=sa.text("'info'::text"), autoincrement=False, nullable=False),
    sa.Column('message', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('agent_log_pkey'))
    )
    op.create_index(op.f('idx_agent_log_level'), 'agent_log', ['level'], unique=False)
    op.create_index(op.f('idx_agent_log_created'), 'agent_log', ['created_at'], unique=False)
    op.create_index(op.f('idx_agent_log_agent'), 'agent_log', ['agent'], unique=False)
    op.create_table('school_emails',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('email_id', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('folder', sa.TEXT(), server_default=sa.text("'INBOX/school'::text"), autoincrement=False, nullable=False),
    sa.Column('sender', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('subject', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('school_id', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('child', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('body_text', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('attachment_text', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('processed_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('school_emails_pkey')),
    sa.UniqueConstraint('email_id', 'folder', name=op.f('school_emails_email_id_folder_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('idx_school_emails_processed'), 'school_emails', ['processed_at'], unique=False)
    # ### end Alembic commands ###